@WebNotes_HostAddress = http://localhost:5057

### Register user1
POST {{WebNotes_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "email": "testuser@domain.com",
  "password": "MySecurePass123!",
  "confirmPassword": "MySecurePass123!"
}

### Login user1
POST {{WebNotes_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "email": "testuser@domain.com",
  "password": "MySecurePass123!"
}

### Register user2
POST {{WebNotes_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "email": "alice@domain.com",
  "password": "aA!111",
  "confirmPassword": "aA!111"
}

### Login user2
POST {{WebNotes_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "email": "alice@domain.com",
  "password": "aA!111"
}